In [1]:
# 必要ライブラリの宣言
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# softmax関数 (9.7.3)
def softmax(x):
    x = x.T
    x_max = x.max(axis=0)
    x = x - x_max
    w = np.exp(x)
    return (w / w.sum(axis=0)).T

In [18]:
x = np.array([[1.,6.3,4.7],[1.,7.,4.7],[1.,5.,1.6],[1.,6.4,5.6],[1.,6.3,5.]])
print(x)
print(x.shape)

[[1.  6.3 4.7]
 [1.  7.  4.7]
 [1.  5.  1.6]
 [1.  6.4 5.6]
 [1.  6.3 5. ]]
(5, 3)


In [19]:
print(x.T)

[[1.  1.  1.  1.  1. ]
 [6.3 7.  5.  6.4 6.3]
 [4.7 4.7 1.6 5.6 5. ]]


In [20]:
x_max = x.max(axis=0)

In [21]:
print(x_max)

[1.  7.  5.6]


In [22]:
x = x - x_max

In [23]:
print(x)
print(x.shape)

[[ 0.  -0.7 -0.9]
 [ 0.   0.  -0.9]
 [ 0.  -2.  -4. ]
 [ 0.  -0.6  0. ]
 [ 0.  -0.7 -0.6]]
(5, 3)


In [24]:
w = np.exp(x)

In [25]:
print(w)
print(w.shape)

[[1.         0.4965853  0.40656966]
 [1.         1.         0.40656966]
 [1.         0.13533528 0.01831564]
 [1.         0.54881164 1.        ]
 [1.         0.4965853  0.54881164]]
(5, 3)


In [26]:
print(w.sum(axis=0))

[5.         2.67731753 2.38026659]


In [28]:
print((w / w.sum(axis=0)))

[[0.2        0.18547867 0.17080846]
 [0.2        0.37350818 0.17080846]
 [0.2        0.05054884 0.00769478]
 [0.2        0.20498564 0.42012101]
 [0.2        0.18547867 0.2305673 ]]


In [27]:
print((w / w.sum(axis=0)).T)

[[0.2        0.2        0.2        0.2        0.2       ]
 [0.18547867 0.37350818 0.05054884 0.20498564 0.18547867]
 [0.17080846 0.17080846 0.00769478 0.42012101 0.2305673 ]]


In [59]:
#np.argmaxについて
# https://deepage.net/features/numpy-argmax.html　を参考に

In [36]:
a = np.random.randint(10, size = 10)

In [37]:
print(a)
print(a.shape)

[3 8 5 6 4 7 3 0 9 9]
(10,)


In [38]:
np.argmax(a)

8

In [54]:
b = np.random.randint(10, size = (3,4))

In [55]:
print(b)
print(b.shape)

[[2 1 5 5]
 [3 7 2 7]
 [1 0 0 8]]
(3, 4)


In [56]:
np.argmax(b)

11

In [57]:
np.argmax(b, axis=0)

array([1, 1, 0, 2])

In [58]:
np.argmax(b, axis=1)

array([2, 1, 3])